apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: storage-metrics-server
rules:
- apiGroups: [""]
  resources: ["nodes", "namespaces", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["nodes/stats", "nodes/proxy"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: storage-metrics-server-server-resources
rules:
- apiGroups: ["custom.metrics.k8s.io"]
  resources: ["*"]
  verbs: ["get", "list"]
