apiVersion: v1
kind: Service
metadata:
  name: storage-metrics-server
spec:
  type: ClusterIP
  ports:
  - name: https
    port: 443
    targetPort: 6443
    protocol: TCP
  selector:
    app.kubernetes.io/name: storage-metrics-server
    app.kubernetes.io/component: apiserver
